version: '3'

services:
  web:
    build: web
    container_name: misp_web
    image: misp:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATA_DIR:-./data}/web:/var/www/MISP
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-misp_db}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL:-admin@admin.test}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE:-admin}
      - MISP_BASEURL=${MISP_BASEURL:-https://localhost}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST:-relay.fqdn}
      - TIMEZONE=${TIMEZONE:-CEST}
    entrypoint: "/bin/bash"
